/*
Post-Deployment Script Template							
--------------------------------------------------------------------------------------
 This file contains SQL statements that will be appended to the build script.		
 Use SQLCMD syntax to include a file in the post-deployment script.			
 Example:      :r .\myfile.sql								
 Use SQLCMD syntax to reference a variable in the post-deployment script.		
 Example:      :setvar TableName MyTable							
               SELECT * FROM [$(TableName)]					
--------------------------------------------------------------------------------------
*/



--OutputColumn                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          
--------------                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          
--PRINT 'Applying Merge to: dbo.AddressType';                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                     
--SET TRANSACTION ISOLATION LEVEL SERIALIZABLE;                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                           
--SET NOCOUNT ON;                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                         
--MERGE    [dbo].[AddressType] AS dest                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            
--USING (VALUES--//////////////////////////////////////////////////////////////////////////////////////////////////                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                       
--(1,'Home', sysdatetime()),
--(2,'Business', sysdatetime())
----\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    
--    ) AS src([Id], [Name], [InsertTimeStamp])
--    ON        1=1 AND dest.[Id] = src.[Id]                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              
--WHEN MATCHED AND (dest.[Name] <> src.[Name])
--THEN UPDATE SET                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                         
--    dest.[Name] = src.[Name],dest.[InsertTimeStamp] = src.[InsertTimeStamp]
--WHEN NOT MATCHED BY TARGET THEN                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                         
--    INSERT([Id], [Name], [InsertTimeStamp])                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                     
--    VALUES(src.[Id],src.[Name],src.[InsertTimeStamp]);
--PRINT 'dbo.AddressType rows affected by MERGE: ' + CAST(@@ROWCOUNT AS VARCHAR(100));                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            

if((select count(*) from businessaddress) > 0)
    return;

insert into businessaddress(ListingUrl,Name,BusinessType,StreetAddress,Language,Locality,Region,ZipCode,PhoneNumber,Tags) values('https://www.b2byellowpages.com/zc/823989999/accountant-brokers-in-91950-ca.html','Angies Bookkeeping Services','Accountant Brokers ','845 E 8th St','Spanish','National City','CA','91950','619-773-6711','Accountants, Accounting & Bookkeeping, Accounting & Bookkeeping Services')
insert into businessaddress(ListingUrl,Name,BusinessType,StreetAddress,Language,Locality,Region,ZipCode,PhoneNumber,Tags) values('https://www.b2byellowpages.com/zc/823989999/accountant-brokers-in-91950-ca.html','Angies Bookkeeping Services','Accountant Brokers ','845 E 8th St','Spanish','National City','CA','91950','619-773-6711','Accountants, Accounting & Bookkeeping, Accounting & Bookkeeping Services')
insert into businessaddress(ListingUrl,Name,BusinessType,StreetAddress,Language,Locality,Region,ZipCode,PhoneNumber,Tags) values('https://www.b2byellowpages.com/zc/823989999/accountant-brokers-in-91950-ca.html','Bookkeeping & Tax','Accountant Brokers ','2720 E Plaza Blvd, Ste U','Spanish','National City','CA','91950','619-475-6144','Accountants, Accounting & Bookkeeping, Bookkeeping Service, Physicians - General, Accounting & Bookkeeping Services')
insert into businessaddress(ListingUrl,Name,BusinessType,StreetAddress,Language,Locality,Region,ZipCode,PhoneNumber,Tags) values('https://www.b2byellowpages.com/zc/823989999/accountant-brokers-in-91950-ca.html','Mercado Michelle-Better Bookkeeping & Tax Services','Accountant Brokers ','44 3rd Ave','Spanish','Chula Vista','CA','91910','619-427-6380','Tax Return Preparation & Filing, Accountants, Accounting & Bookkeeping, Bookkeeping Service, Accountants Certified Public, Tax Preparation, Accounting & Bookkeeping Services')
insert into businessaddress(ListingUrl,Name,BusinessType,StreetAddress,Language,Locality,Region,ZipCode,PhoneNumber,Tags) values('https://www.b2byellowpages.com/zc/823989999/accountant-brokers-in-91950-ca.html','AA Accounting Plus','Accountant Brokers ','1336 Roosevelt Ave','Spanish','National City','CA','91950','619-234-3098','Accountants, Accounting & Bookkeeping, Accounting & Bookkeeping Services')
insert into businessaddress(ListingUrl,Name,BusinessType,StreetAddress,Language,Locality,Region,ZipCode,PhoneNumber,Tags) values('https://www.b2byellowpages.com/zc/823989999/accountant-brokers-in-91950-ca.html','ACI CPA APC','Accountant Brokers ','371 E St','Spanish','Chula Vista','CA','91910','619-422-1348','Accountants, Accounting & Bookkeeping, Financial Planning Consultants & Services, Accountants Certified Public, Financial Consultants, Financial Planning & Investments, Accounting & Bookkeeping Services')
insert into businessaddress(ListingUrl,Name,BusinessType,StreetAddress,Language,Locality,Region,ZipCode,PhoneNumber,Tags) values('https://www.b2byellowpages.com/zc/823989999/accountant-brokers-in-91950-ca.html','Express Pawn Shops','Accountant Brokers ','1050 Highland Ave, Ste E','Spanish','National City','CA','91950','619-474-5566','Pawnbrokers, Accounting & Bookkeeping, Pawn Shops & Discount Stores, Accountant Brokers, Accounting & Bookkeeping Services')
insert into businessaddress(ListingUrl,Name,BusinessType,StreetAddress,Language,Locality,Region,ZipCode,PhoneNumber,Tags) values('https://www.b2byellowpages.com/zc/823989999/accountant-brokers-in-91950-ca.html','Blanco Tax & Accounting','Accountant Brokers ','265 E St','English','Chula Vista','CA','91910','619-207-0717','Tax Return Preparation & Filing, Accountants, Accounting & Bookkeeping, Tax Preparation, Accounting & Bookkeeping Services')
insert into businessaddress(ListingUrl,Name,BusinessType,StreetAddress,Language,Locality,Region,ZipCode,PhoneNumber,Tags) values('https://www.b2byellowpages.com/zc/823989999/accountant-brokers-in-91950-ca.html','Bliss Robert CPA 7595','Accountant Brokers ','378 E St, Ste B','Spanish','Chula Vista','CA','91910','619-585-7595','Tax Return Preparation & Filing, Notaries Public Services, Accountants, Accounting & Bookkeeping, Bookkeeping Service, Accountants Certified Public, Tax Preparation, Accounting & Bookkeeping Services, Public & Social Services')
insert into businessaddress(ListingUrl,Name,BusinessType,StreetAddress,Language,Locality,Region,ZipCode,PhoneNumber,Tags) values('https://www.b2byellowpages.com/zc/823989999/accountant-brokers-in-91950-ca.html','Alvarez Bookkeeping Services','Accountant Brokers ','247 E St','Spanish','Chula Vista','CA','91910','619-421-7051','Accountants, Accounting & Bookkeeping, Bookkeeping Service, Accounting & Bookkeeping Services')
insert into businessaddress(ListingUrl,Name,BusinessType,StreetAddress,Language,Locality,Region,ZipCode,PhoneNumber,Tags) values('https://www.b2byellowpages.com/zc/823989999/accountant-brokers-in-91950-ca.html','Robert Bliss CPA','Accountant Brokers ','378 E St, Ste B','Spanish','Chula Vista','CA','91910','619-585-7595','Tax Return Preparation & Filing, Notaries Public Services, Accountants, Accounting & Bookkeeping, Bookkeeping Service, Accountants Certified Public, Tax Preparation, Accounting & Bookkeeping Services, Public & Social Services')
insert into businessaddress(ListingUrl,Name,BusinessType,StreetAddress,Language,Locality,Region,ZipCode,PhoneNumber,Tags) values('https://www.b2byellowpages.com/zc/823997998/accountants-in-91950-ca.html','Angies Bookkeeping Services','Accountants ','845 E 8th St','English','National City','CA','91950','619-773-6711','Accountants, Accounting & Bookkeeping, Accounting & Bookkeeping Services')
insert into businessaddress(ListingUrl,Name,BusinessType,StreetAddress,Language,Locality,Region,ZipCode,PhoneNumber,Tags) values('https://www.b2byellowpages.com/zc/823997998/accountants-in-91950-ca.html','Bookkeeping & Tax','Accountants ','2720 E Plaza Blvd, Ste U','Spanish','National City','CA','91950','619-475-6144','Accountants, Accounting & Bookkeeping, Bookkeeping Service, Physicians - General, Accounting & Bookkeeping Services')
insert into businessaddress(ListingUrl,Name,BusinessType,StreetAddress,Language,Locality,Region,ZipCode,PhoneNumber,Tags) values('https://www.b2byellowpages.com/zc/823997998/accountants-in-91950-ca.html','AA Accounting Plus','Accountants ','1336 Roosevelt Ave','English','National City','CA','91950','619-234-3098','Accountants, Accounting & Bookkeeping, Accounting & Bookkeeping Services')
insert into businessaddress(ListingUrl,Name,BusinessType,StreetAddress,Language,Locality,Region,ZipCode,PhoneNumber,Tags) values('https://www.b2byellowpages.com/zc/823997998/accountants-in-91950-ca.html','Mercado Michelle-Better Bookkeeping & Tax Services','Accountants ','44 3rd Ave','English','Chula Vista','CA','91910','619-427-6380','Tax Return Preparation & Filing, Accountants, Accounting & Bookkeeping, Bookkeeping Service, Accountants Certified Public, Tax Preparation, Accounting & Bookkeeping Services')
insert into businessaddress(ListingUrl,Name,BusinessType,StreetAddress,Language,Locality,Region,ZipCode,PhoneNumber,Tags) values('https://www.b2byellowpages.com/zc/823997998/accountants-in-91950-ca.html','ACI CPA APC','Accountants ','371 E St','Spanish','Chula Vista','CA','91910','619-422-1348','Accountants, Accounting & Bookkeeping, Financial Planning Consultants & Services, Accountants Certified Public, Financial Consultants, Financial Planning & Investments, Accounting & Bookkeeping Services')
insert into businessaddress(ListingUrl,Name,BusinessType,StreetAddress,Language,Locality,Region,ZipCode,PhoneNumber,Tags) values('https://www.b2byellowpages.com/zc/823997998/accountants-in-91950-ca.html','Blanco Tax & Accounting','Accountants ','265 E St','English','Chula Vista','CA','91910','619-207-0717','Tax Return Preparation & Filing, Accountants, Accounting & Bookkeeping, Tax Preparation, Accounting & Bookkeeping Services')
insert into businessaddress(ListingUrl,Name,BusinessType,StreetAddress,Language,Locality,Region,ZipCode,PhoneNumber,Tags) values('https://www.b2byellowpages.com/zc/823997998/accountants-in-91950-ca.html','Robert Bliss CPA','Accountants ','378 E St, Ste B','English','Chula Vista','CA','91910','619-585-7595','Tax Return Preparation & Filing, Notaries Public Services, Accountants, Accounting & Bookkeeping, Bookkeeping Service, Accountants Certified Public, Tax Preparation, Accounting & Bookkeeping Services, Public & Social Services')
insert into businessaddress(ListingUrl,Name,BusinessType,StreetAddress,Language,Locality,Region,ZipCode,PhoneNumber,Tags) values('https://www.b2byellowpages.com/zc/823997998/accountants-in-91950-ca.html','Alvarez Bookkeeping Services','Accountants ','247 E St','Spanish','Chula Vista','CA','91910','619-421-7051','Accountants, Accounting & Bookkeeping, Bookkeeping Service, Accounting & Bookkeeping Services')
insert into businessaddress(ListingUrl,Name,BusinessType,StreetAddress,Language,Locality,Region,ZipCode,PhoneNumber,Tags) values('https://www.b2byellowpages.com/zc/823997998/accountants-in-91950-ca.html','Bliss Robert CPA 7595','Accountants ','378 E St, Ste B','Spanish','Chula Vista','CA','91910','619-585-7595','Tax Return Preparation & Filing, Notaries Public Services, Accountants, Accounting & Bookkeeping, Bookkeeping Service, Accountants Certified Public, Tax Preparation, Accounting & Bookkeeping Services, Public & Social Services')
insert into businessaddress(ListingUrl,Name,BusinessType,StreetAddress,Language,Locality,Region,ZipCode,PhoneNumber,Tags) values('https://www.b2byellowpages.com/zc/823997998/accountants-in-91950-ca.html','Galindo Ruiz Guadalupe','Accountants ','590 G St','Spanish','Chula Vista','CA','91910','619-427-2575','Accountants, Accounting & Bookkeeping, Tax Consultants, Tax Consultants & Representatives, Accounting & Bookkeeping Services')
insert into businessaddress(ListingUrl,Name,BusinessType,StreetAddress,Language,Locality,Region,ZipCode,PhoneNumber,Tags) values('https://www.b2byellowpages.com/zc/823998999/accountants-certified-public-in-91950-ca.html','Income Tax Services','Accountants Certified Public ','2930 E 8th St','English','National City','CA','91950','619-267-1393','Tax Return Preparation & Filing, Accountants Certified Public, Tax Preparation, Accounting & Bookkeeping Services')
insert into businessaddress(ListingUrl,Name,BusinessType,StreetAddress,Language,Locality,Region,ZipCode,PhoneNumber,Tags) values('https://www.b2byellowpages.com/zc/823998999/accountants-certified-public-in-91950-ca.html','Dale Yabu CPA','Accountants Certified Public ','434 Highland Ave','Spanish','National City','CA','91950','619-474-6751','Accountants Certified Public, Accounting & Bookkeeping Services')
insert into businessaddress(ListingUrl,Name,BusinessType,StreetAddress,Language,Locality,Region,ZipCode,PhoneNumber,Tags) values('https://www.b2byellowpages.com/zc/823998999/accountants-certified-public-in-91950-ca.html','Hepp Bookeepmng & Tax Service','Accountants Certified Public ','46 3rd Ave','Spanish','Chula Vista','CA','91910','619-422-8316','Tax Return Preparation & Filing, Accountants Certified Public, Tax Preparation, Accounting & Bookkeeping Services')
insert into businessaddress(ListingUrl,Name,BusinessType,StreetAddress,Language,Locality,Region,ZipCode,PhoneNumber,Tags) values('https://www.b2byellowpages.com/zc/823998999/accountants-certified-public-in-91950-ca.html','Mercado Michelle-Better Bookkeeping & Tax Services','Accountants Certified Public ','44 3rd Ave','Spanish','Chula Vista','CA','91910','619-427-6380','Tax Return Preparation & Filing, Accountants, Accounting & Bookkeeping, Bookkeeping Service, Accountants Certified Public, Tax Preparation, Accounting & Bookkeeping Services')
insert into businessaddress(ListingUrl,Name,BusinessType,StreetAddress,Language,Locality,Region,ZipCode,PhoneNumber,Tags) values('https://www.b2byellowpages.com/zc/823998999/accountants-certified-public-in-91950-ca.html','Ci CPA A APC','Accountants Certified Public ','371 E St','Spanish','Chula Vista','CA','91910','619-422-1348','Accountants Certified Public, Accounting & Bookkeeping Services')
insert into businessaddress(ListingUrl,Name,BusinessType,StreetAddress,Language,Locality,Region,ZipCode,PhoneNumber,Tags) values('https://www.b2byellowpages.com/zc/823998999/accountants-certified-public-in-91950-ca.html','ACI CPA APC','Accountants Certified Public ','371 E St','Spanish','Chula Vista','CA','91910','619-422-1348','Accountants, Accounting & Bookkeeping, Financial Planning Consultants & Services, Accountants Certified Public, Financial Consultants, Financial Planning & Investments, Accounting & Bookkeeping Services')
insert into businessaddress(ListingUrl,Name,BusinessType,StreetAddress,Language,Locality,Region,ZipCode,PhoneNumber,Tags) values('https://www.b2byellowpages.com/zc/823998999/accountants-certified-public-in-91950-ca.html','Robert Bliss CPA','Accountants Certified Public ','378 E St, Ste B','English','Chula Vista','CA','91910','619-585-7595','Tax Return Preparation & Filing, Notaries Public Services, Accountants, Accounting & Bookkeeping, Bookkeeping Service, Accountants Certified Public, Tax Preparation, Accounting & Bookkeeping Services, Public & Social Services')
insert into businessaddress(ListingUrl,Name,BusinessType,StreetAddress,Language,Locality,Region,ZipCode,PhoneNumber,Tags) values('https://www.b2byellowpages.com/zc/823998999/accountants-certified-public-in-91950-ca.html','Rogers Don Tax Service','Accountants Certified Public ','326 E St','English','Chula Vista','CA','91910','619-422-8000','Tax Return Preparation & Filing, Bookkeeping Service, Accountants Certified Public, Tax Preparation, Accounting & Bookkeeping Services')
insert into businessaddress(ListingUrl,Name,BusinessType,StreetAddress,Language,Locality,Region,ZipCode,PhoneNumber,Tags) values('https://www.b2byellowpages.com/zc/823998999/accountants-certified-public-in-91950-ca.html','Bliss Robert CPA 7595','Accountants Certified Public ','378 E St, Ste B','English','Chula Vista','CA','91910','619-585-7595','Tax Return Preparation & Filing, Notaries Public Services, Accountants, Accounting & Bookkeeping, Bookkeeping Service, Accountants Certified Public, Tax Preparation, Accounting & Bookkeeping Services, Public & Social Services')
insert into businessaddress(ListingUrl,Name,BusinessType,StreetAddress,Language,Locality,Region,ZipCode,PhoneNumber,Tags) values('https://www.b2byellowpages.com/zc/823998999/accountants-certified-public-in-91950-ca.html','Alvarez Bookkeeping Services','Accountants Certified Public ','249 E St','English','Chula Vista','CA','91910','619-421-7051','Accountants Certified Public, Accounting & Bookkeeping Services')
insert into businessaddress(ListingUrl,Name,BusinessType,StreetAddress,Language,Locality,Region,ZipCode,PhoneNumber,Tags) values('https://www.b2byellowpages.com/zc/823999999/accounting-bookkeeping-services-in-91950-ca.html','Angies Bookkeeping Services','Accounting & Bookkeeping Services ','845 E 8th St','English','National City','CA','91950','619-773-6711','Accountants, Accounting & Bookkeeping, Accounting & Bookkeeping Services')
insert into businessaddress(ListingUrl,Name,BusinessType,StreetAddress,Language,Locality,Region,ZipCode,PhoneNumber,Tags) values('https://www.b2byellowpages.com/zc/823999999/accounting-bookkeeping-services-in-91950-ca.html','DD Tax Multiservices','Accounting & Bookkeeping Services ','1625 Sweetwater Rd','English','National City','CA','91950','619-477-1189','Tax Consultants, Tax Consultants & Representatives, Accounting & Bookkeeping Services')
insert into businessaddress(ListingUrl,Name,BusinessType,StreetAddress,Language,Locality,Region,ZipCode,PhoneNumber,Tags) values('https://www.b2byellowpages.com/zc/823999999/accounting-bookkeeping-services-in-91950-ca.html','Bookkeeping & Tax','Accounting & Bookkeeping Services ','2720 E Plaza Blvd, Ste U','English','National City','CA','91950','619-475-6144','Accountants, Accounting & Bookkeeping, Bookkeeping Service, Physicians - General, Accounting & Bookkeeping Services')
insert into businessaddress(ListingUrl,Name,BusinessType,StreetAddress,Language,Locality,Region,ZipCode,PhoneNumber,Tags) values('https://www.b2byellowpages.com/zc/823999999/accounting-bookkeeping-services-in-91950-ca.html','Income Tax Services','Accounting & Bookkeeping Services ','2930 E 8th St','English','National City','CA','91950','619-267-1393','Tax Return Preparation & Filing, Accountants Certified Public, Tax Preparation, Accounting & Bookkeeping Services')
insert into businessaddress(ListingUrl,Name,BusinessType,StreetAddress,Language,Locality,Region,ZipCode,PhoneNumber,Tags) values('https://www.b2byellowpages.com/zc/823999999/accounting-bookkeeping-services-in-91950-ca.html','AA Accounting Plus','Accounting & Bookkeeping Services ','1336 Roosevelt Ave','English','National City','CA','91950','619-234-3098','Accountants, Accounting & Bookkeeping, Accounting & Bookkeeping Services')
insert into businessaddress(ListingUrl,Name,BusinessType,StreetAddress,Language,Locality,Region,ZipCode,PhoneNumber,Tags) values('https://www.b2byellowpages.com/zc/823999999/accounting-bookkeeping-services-in-91950-ca.html','Msc Physician Billing Services','Accounting & Bookkeeping Services ','1615 Sweetwater Rd, Ste B','English','National City','CA','91950','619-474-9640','Medical Equipment & Supplies, Medical Billing Service, Medical Management Services & Consulting, Medical Management Consultants, Accounting & Bookkeeping Services')
insert into businessaddress(ListingUrl,Name,BusinessType,StreetAddress,Language,Locality,Region,ZipCode,PhoneNumber,Tags) values('https://www.b2byellowpages.com/zc/823999999/accounting-bookkeeping-services-in-91950-ca.html','Casas Melinda','Accounting & Bookkeeping Services ','1615 Sweetwater Rd','English','National City','CA','91950','619-474-9350','Medical Billing Service, Accounting & Bookkeeping Services')
insert into businessaddress(ListingUrl,Name,BusinessType,StreetAddress,Language,Locality,Region,ZipCode,PhoneNumber,Tags) values('https://www.b2byellowpages.com/zc/823999999/accounting-bookkeeping-services-in-91950-ca.html','Dale Yabu CPA','Accounting & Bookkeeping Services ','434 Highland Ave','English','National City','CA','91950','619-474-6751','Accountants Certified Public, Accounting & Bookkeeping Services')
insert into businessaddress(ListingUrl,Name,BusinessType,StreetAddress,Language,Locality,Region,ZipCode,PhoneNumber,Tags) values('https://www.b2byellowpages.com/zc/823999999/accounting-bookkeeping-services-in-91950-ca.html','Express Pawn Shops','Accounting & Bookkeeping Services ','1050 Highland Ave, Ste E','English','National City','CA','91950','619-474-5566','Pawnbrokers, Accounting & Bookkeeping, Pawn Shops & Discount Stores, Accountant Brokers, Accounting & Bookkeeping Services')
insert into businessaddress(ListingUrl,Name,BusinessType,StreetAddress,Language,Locality,Region,ZipCode,PhoneNumber,Tags) values('https://www.b2byellowpages.com/zc/823999999/accounting-bookkeeping-services-in-91950-ca.html','John Chan','Accounting & Bookkeeping Services ','434 Highland Ave','English','National City','CA','91950','619-474-6751','Bookkeeping Service, Accounting & Bookkeeping Services')
insert into businessaddress(ListingUrl,Name,BusinessType,StreetAddress,Language,Locality,Region,ZipCode,PhoneNumber,Tags) values('https://www.b2byellowpages.com/zc/853998999/acupuncturist-in-91950-ca.html','Ticzon Acupuncture Clinic','Acupuncturist ','550 E 8th St','English','National City','CA','91950','619-773-7355','Alternative Medicine, Medical Laboratories, Laboratories Medical, Acupuncturist')
insert into businessaddress(ListingUrl,Name,BusinessType,StreetAddress,Language,Locality,Region,ZipCode,PhoneNumber,Tags) values('https://www.b2byellowpages.com/zc/853998999/acupuncturist-in-91950-ca.html','Raul Caoili L AC','Acupuncturist ','1615 Sweetwater Rd, Ste J','English','National City','CA','91950','619-474-8649','Alternative Medicine, Acupuncturist')
insert into businessaddress(ListingUrl,Name,BusinessType,StreetAddress,Language,Locality,Region,ZipCode,PhoneNumber,Tags) values('https://www.b2byellowpages.com/zc/853998999/acupuncturist-in-91950-ca.html','Total Wellness Health Center','Acupuncturist ','316 E H St, Ste 701-A','English','Chula Vista','CA','91910','619-422-6130','Clinics Medical, Chiropractors, Alternative Medicine, Hospitals, Clinics & Medical Centers, Acupuncturist')
insert into businessaddress(ListingUrl,Name,BusinessType,StreetAddress,Language,Locality,Region,ZipCode,PhoneNumber,Tags) values('https://www.b2byellowpages.com/zc/853998999/acupuncturist-in-91950-ca.html','Ching-Chuan Tsai Mark DC Lac','Acupuncturist ','316 E H St, Ste 701-A','English','Chula Vista','CA','91910','619-422-6130','Chiropractors, Alternative Medicine, Acupuncturist')
insert into businessaddress(ListingUrl,Name,BusinessType,StreetAddress,Language,Locality,Region,ZipCode,PhoneNumber,Tags) values('https://www.b2byellowpages.com/zc/853998999/acupuncturist-in-91950-ca.html','Bonita Acupuncture & Massage Clinic','Acupuncturist ','4392 Bonita Rd','English','Bonita','CA','91902','619-267-6050','Alternative Medicine, Acupuncturist, Massage')
insert into businessaddress(ListingUrl,Name,BusinessType,StreetAddress,Language,Locality,Region,ZipCode,PhoneNumber,Tags) values('https://www.b2byellowpages.com/zc/853998999/acupuncturist-in-91950-ca.html','Acu-Care Health Centers','Acupuncturist ','4514 Bonita Rd','English','Bonita','CA','91902','619-470-4714','Clinics Medical, Alternative Medicine, Hospitals, Clinics & Medical Centers, Acupressure, Acupuncturist')
insert into businessaddress(ListingUrl,Name,BusinessType,StreetAddress,Language,Locality,Region,ZipCode,PhoneNumber,Tags) values('https://www.b2byellowpages.com/zc/853998999/acupuncturist-in-91950-ca.html','Acupuncture Medical Clinic','Acupuncturist ','1125 9th Ave','English','San Diego','CA','92101','858-483-7795','Alternative Medicine, Acupuncturist')
insert into businessaddress(ListingUrl,Name,BusinessType,StreetAddress,Language,Locality,Region,ZipCode,PhoneNumber,Tags) values('https://www.b2byellowpages.com/zc/853998999/acupuncturist-in-91950-ca.html','to The Point Gaslamp Acupuncture','Acupuncturist ','711 4th Ave','English','San Diego','CA','92101','619-955-1050','Alternative Medicine, Acupuncturist')
insert into businessaddress(ListingUrl,Name,BusinessType,StreetAddress,Language,Locality,Region,ZipCode,PhoneNumber,Tags) values('https://www.b2byellowpages.com/zc/853998999/acupuncturist-in-91950-ca.html','Island Acupuncture','Acupuncturist ','1222 1st St','English','Coronado','CA','92118','619-435-2522','Alternative Medicine, Acupuncturist')